---

- hosts: all
  vars:
    play_gather: true
    extra_value: ""
  gather_facts: "{{ play_gather }}"
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: set a fact man
      set_fact:
        foo: "bar{{ extra_value }}"
        bar:
          a:
            b:
              - "c"
              - "d"
        cacheable: "{{ set_fact_cacheable | default(false) }}"
